import SwiftUI
import UIKit

/// Renders a Check result to a shareable PDF using `ImageRenderer` (to rasterize a
/// SwiftUI report card) placed onto a US-Letter page via `UIGraphicsPDFRenderer`.
enum PDFReportService {

    /// Writes a PDF to a temp URL and returns it, or nil on failure.
    @MainActor
    static func generate(projectName: String,
                         platform: String,
                         result: ScoreEngine.Result,
                         date: Date = .now) -> URL? {
        let pageWidth: CGFloat = 612   // 8.5" * 72
        let pageHeight: CGFloat = 792  // 11" * 72
        let margin: CGFloat = 48
        let contentWidth = pageWidth - margin * 2

        let report = ReportCard(projectName: projectName, platform: platform,
                                result: result, date: date)
            .frame(width: contentWidth)
            .padding(0)

        let renderer = ImageRenderer(content: report)
        renderer.scale = 3
        guard let image = renderer.uiImage else { return nil }

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("Ally-\(projectName)-report.pdf")

        let pdf = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))
        do {
            try pdf.writePDF(to: url) { ctx in
                ctx.beginPage()
                let aspect = image.size.height / image.size.width
                let drawWidth = contentWidth
                let drawHeight = drawWidth * aspect
                image.draw(in: CGRect(x: margin, y: margin, width: drawWidth, height: drawHeight))
            }
            return url
        } catch {
            return nil
        }
    }
}

/// The visual laid onto the PDF page. Plain, print-friendly (no app backdrop).
private struct ReportCard: View {
    let projectName: String
    let platform: String
    let result: ScoreEngine.Result
    let date: Date

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.xl) {
            VStack(alignment: .leading, spacing: Spacing.xs) {
                Text("ALLY · ACCESSIBILITY SELF-ASSESSMENT")
                    .font(Typography.eyebrow)
                    .foregroundStyle(ColorTokens.brandPrimaryInk)
                Text(projectName)
                    .font(Typography.display)
                    .foregroundStyle(.black)
                Text("\(platform) · \(date.formatted(date: .abbreviated, time: .omitted))")
                    .font(Typography.subheadline)
                    .foregroundStyle(.secondary)
            }

            HStack(alignment: .center, spacing: Spacing.xl) {
                VStack(spacing: 0) {
                    Text("\(result.overall)")
                        .font(.system(size: 72, weight: .heavy, design: .rounded))
                        .foregroundStyle(.black)
                    Text("out of 100").font(Typography.footnote).foregroundStyle(.secondary)
                }
                VStack(alignment: .leading, spacing: Spacing.sm) {
                    ForEach(result.byCategory) { cs in
                        HStack {
                            Circle().fill(cs.category.color).frame(width: 10, height: 10)
                            Text(cs.category.title).font(Typography.subheadline).foregroundStyle(.black)
                            Spacer()
                            Text("\(cs.score)").font(Typography.bodyEmph).foregroundStyle(.black)
                        }
                    }
                }
            }

            if !result.needsWork.isEmpty {
                VStack(alignment: .leading, spacing: Spacing.sm) {
                    Text("Focus areas").font(Typography.headline).foregroundStyle(.black)
                    ForEach(result.needsWork.prefix(8), id: \.item.id) { entry in
                        HStack(alignment: .top, spacing: Spacing.sm) {
                            Text(entry.answer.rawValue)
                                .font(Typography.caption2.weight(.bold))
                                .foregroundStyle(.white)
                                .padding(.horizontal, 6).padding(.vertical, 2)
                                .background(Capsule().fill(entry.answer == .no ? Color.red : Color.orange))
                            VStack(alignment: .leading, spacing: 1) {
                                Text(entry.item.question).font(Typography.footnote).foregroundStyle(.black)
                                Text("WCAG \(entry.item.wcagRef) · \(entry.item.wcagTitle)")
                                    .font(Typography.caption2).foregroundStyle(.secondary)
                            }
                        }
                    }
                }
            }

            Text("Generated by Ally. A self-assessment aid, not a certified audit.")
                .font(Typography.caption2)
                .foregroundStyle(.secondary)
        }
        .padding(Spacing.xl)
        .background(Color.white)
    }
}
